language: cpp

os:
  - linux

dist: bionic

compiler:
  - clang
  - gcc

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - git
      - gcc-7
      - g++-7
      - libboost-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
