language: cpp

os:
  - linux

dist: bionic

compiler:
  - clang
  - gcc

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - cmake
      - git
      - gcc-7.4
      - g++-7.4
      - libboost-all-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
